#!/usr/bin/env python2.7
import os
import argparse


description = "Rename the output from MakeMKV. (C) 2015 Andrew Scagnelli"
add_help = "The input prefix to change (eg title in title00.mkv)"
output_help = "The output prefix"
offset_help = "The offset between the input and output files."
start_help = "The value to start counting from."
dir_help = "The directory to loop through."
extension_help = "File extension to monitor."
epilog = "(C) 2015 Andrew Scagnelli.  Available under the GNU GPL."


def main():
    parser = argparse.ArgumentParser(description=description,
                                     epilog=epilog)
    parser.add_argument('--output', required=True, help=output_help)
    parser.add_argument('--prefix', required=False, default="title",
                        type=str, help=add_help)
    parser.add_argument('--offset', required=False, default=1,
                        type=int, help=offset_help)
    parser.add_argument('--start', required=False, default="0",
                        type=int, help=start_help)
    parser.add_argument('--dir', required=False, default=".", help=dir_help)
    parser.add_argument('--extension', required=False, default="mkv",
                        help=extension_help)

    args = parser.parse_args()
    count = args.start

    for file in os.listdir(args.dir):
        infile = args.prefix + str(count).zfill(2) + "." + args.extension
        offset = count + int(args.offset)
        output = args.output + str(offset).zfill(2) + "." + args.extension
        if (os.path.isfile(output)):
            print("Output file " + output + " already exists, cancelling run")
            exit()
        elif (not os.path.isfile(infile)):
            print("Input file " + infile + " does not exist, cancelling run")
            exit()

    for file in os.listdir(args.dir):
        if args.prefix not in file:
            continue

        infile = args.prefix + str(count).zfill(2) + "." + args.extension
        offset = count + args.offset
        output = args.output + str(offset).zfill(2) + "." + args.extension

        print "Renaming " + infile + " to " + output

        if (os.path.isfile(output)):
            print("Output file " + output + " already exists, aborting")
            exit()
        elif (not os.path.isfile(infile)):
            print("Input file " + infile + " does not exist, aborting")
            exit()
        else:
            os.rename(args.dir + "/" + infile, args.dir + "/" + output)
            count = count + 1


if __name__ == "__main__":
    main()
